baseURL = "http://www.worldtimeclock.tk/"
languageCode = "en-us"
title = "World Time Clock"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "robotsTXT"]
disableHugoGeneratorInject = true
publishDir = "docs"
theme = "clocks"
